blank_issues_enabled: false
contact_links:
  - name: Community invite
    url: https://m.me/j/AbbxfofRAX3TyND-/?send_source=gc%3Acopy_invite_link_c
    about: Join the Ground Zero community for discussion and support.
